import { notoSans, impact } from "./fonts";
import "./globals.css";

import Header from "./components/Header";
import NavBar from "./components/nav/NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={notoSans.className}>
      <body className="w-full max-w-screen-2xl overflow-auto mx-auto">
        <header className={impact.className}>
          <Header />
        </header>
        <main className="flex flex-col xl:flex-row">
          <nav className="sticky top-0 w-full h-full xl:basis-1/5">
            <NavBar />
          </nav>
          <section className="w-full xl:basis-3/4">{children}</section>
        </main>
        <div id="addStudyModal" />
      </body>
    </html>
  );
}
