import Header from "./components/Header";
import { notoSans, impact } from "./fonts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={notoSans.className}>
      <body className="w-full max-w-screen-2xl overflow-auto mx-auto">
        <header className={impact.className}>
          <Header />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
